---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=$TZ
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG}/jellyseerr:/app/config
    restart: unless-stopped
    # labels:
    #   - "com.centurylinklabs.watchtower.monitor-only=true"
