# reference docs
# https://docs.frigate.video/configuration/camera_specific/#reolink-cameras

mqtt:
  enabled: true
  host: 10.27.27.13
  user: david
  password: mqttpassword

detectors:
  coral:
    type: edgetpu
    device: usb

# Enable hardware acceleration for AMD GPU
ffmpeg:
  hwaccel_args: preset-vaapi

# database:
#  path: /config/frigate.db

go2rtc:
  streams:
    Lobby:
    - "ffmpeg:http://10.40.40.9/flv?&app=bcs&stream=channel0_main.bcs&user=admin&password=NkZkdMJfAmFL6VuSc2iX#video=copy#audio=copy#audio=opus"
    Lobby_sub:
    - "ffmpeg:http://10.40.40.9/flv?&app=bcs&stream=channel0_ext.bcs&user=admin&password=NkZkdMJfAmFL6VuSc2iX"
    Front:
    - "ffmpeg:http://10.40.40.7/flv?&app=bcs&stream=channel0_main.bcs&user=admin&password=9djzGHhxDyswq7#video=copy#audio=copy#audio=opus"
    # - http://10.40.40.7/flv?&app=bcs&stream=channel0_main.bcs&user=admin&password=9djzGHhxDyswq7
    Front_sub:
    - "ffmpeg:http://10.40.40.7/flv?&app=bcs&stream=channel0_ext.bcs&user=admin&password=9djzGHhxDyswq7"
    Back:
    - "ffmpeg:http://10.40.40.6/flv?&app=bcs&stream=channel0_main.bcs&user=admin&password=Gr5dD9bR6PpCi6#video=copy#audio=copy#audio=opus"
    Back_sub:
    - "ffmpeg:http://10.40.40.6/flv?&app=bcs&stream=channel0_ext.bcs&user=admin&password=Gr5dD9bR6PpCi6"
    Doorbell:
    - "ffmpeg:http://10.40.40.5/flv?&app=bcs&stream=channel0_main.bcs&user=admin&password=m6EnwRqypedjUG#video=copy#audio=copy#audio=opus"
    - rtsp://10.40.40.5/Preview_01_sub
    Doorbell_sub:
    - "ffmpeg:http://10.40.40.5/flv?&app=bcs&stream=channel0_ext.bcs&user=admin&password=m6EnwRqypedjUG"
    Playroom:
    - "ffmpeg:http://10.40.40.8/flv?&app=bcs&stream=channel0_main.bcs&user=admin&password=k5nBuwsVhuXTgPjutRXd#video=copy#audio=copy#audio=opus"
    Playroom_sub:
    - "ffmpeg:http://10.40.40.8/flv?&app=bcs&stream=channel0_ext.bcs&user=admin&password=k5nBuwsVhuXTgPjutRXd"
    Livingroom:
    # - "ffmpeg:http://10.27.27.59/flv?&app=bcs&stream=channel0_main.bcs&user=admin&password=ar82%$*83^7CNXGJ#video=copy#audio=copy#audio=opus"
    - "ffmpeg:http://10.27.27.59/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=P5oScfDCxgCQWzP4EG2Q#video=copy#audio=copy#audio=opus"
    Livingroom_sub:
    - "ffmpeg:http://10.27.27.59/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=P5oScfDCxgCQWzP4EG2Q"

cameras:
  Doorbell:
    ffmpeg:
      # output_args:
      #   record: preset-record-generic-audio-copy
      inputs:
      # - path: rtsp://127.0.0.1:8554/Doorbell?video=copy&audio=aac
      - path: rtsp://127.0.0.1:8554/Doorbell
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Doorbell_sub?#video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
      width: 640   # Optimized detection resolution
      height: 480
      fps: 5       # Reduced FPS for performance
    motion:
      mask:
      - 330,0,610,0,502,299,226,285
    objects:
      track:
       # - car
      - person
     # filters:
      #  car:
      #    mask:
      #      - 590,449,394,430,417,368,573,372,1133,356,1180,432,842,482,627,509
    # zones:
    #   parking_spots:
    #     coordinates: 516,507,516,447,357,447,307,516
    #     objects:
    #       - car

  Front:
    ffmpeg:
      # output_args:
      #   record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/Front#?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Front_sub#?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
      width: 640   # Optimized detection resolution
      height: 480
      fps: 5       # Reduced FPS for performance
    motion:
      mask:
      - 0,0,329,0,255,324,0,345
    objects:
      track:
        #- car
      - person
      filters:
        person:
          threshold: 0.60
        #car:
        #  mask:
        #    - 1280,267,1280,102,1066,48,878,47,318,78,317,148,416,225,498,340
    zones:
      steps:
        coordinates: 374,720,1280,720,896,672,896,408,751,395,524,354,183,438
      # parking_spots:
      #   coordinates: 153,374,149,268,368,245,419,346
      #   objects:
      #     - car

  Back:
    ffmpeg:
      # output_args:
      #   record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/Back#?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Back_sub?#video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
    objects:
      track:
      - person
      filters:
        person:
          threshold: 0.75
    detect:
      enabled: true
      width: 640   # Optimized detection resolution
      height: 480
      fps: 5       # Reduced FPS for performance

  Playroom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/Playroom#?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Playroom_sub#?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
    objects:
      track:
      - person
      filters:
        person:
          threshold: 0.75
    detect:
      enabled: true
      width: 640   # Optimized detection resolution
      height: 480
      fps: 5       # Reduced FPS for performance

  Lobby:
    ffmpeg:
      # output_args:
        # record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/Lobby#?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Lobby_sub#?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
    objects:
      track:
      - person
      filters:
        person:
          threshold: 0.75
    detect:
      enabled: true
      width: 640   # Optimized detection resolution
      height: 480
      fps: 5       # Reduced FPS for performance

  Livingroom:
    ffmpeg:
      # output_args:
      #   record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/Livingroom#?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Livingroom_sub#?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
    objects:
      track:
      - person
      filters:
        person:
          threshold: 0.75
    detect:
      enabled: true
      width: 640   # Optimized detection resolution
      height: 480
      fps: 5       # Reduced FPS for performance

# objects:
#   track:
#     - person
#   filters:
#     person:
#       threshold: 0.75

snapshots:
  enabled: true

record:
  enabled: true
  retain:
    days: 7    # Reduced from 15 days for better storage management
    mode: motion
  events:
    retain:
      default: 10  # Reduced from 20 for better storage management
      mode: active_objects
