---
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
    volumes:
      - ${CONFIG}/changedetection:/config
    ports:
      - 5001:5000
    restart: unless-stopped

  browser-chrome:
    hostname: browser-chrome
    container_name: browser-chrome
    image: selenium/standalone-chrome-debug:3.141.59
    environment:
        - VNC_NO_PASSWORD=1
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1080
        - SCREEN_DEPTH=24
    volumes:
        # Workaround to avoid the browser crashing inside a docker container
        # See https://github.com/SeleniumHQ/docker-selenium#quick-start
        - /dev/shm:/dev/shm
    restart: unless-stopped