---
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    # network_mode: host
    restart: unless-stopped
    volumes:
      - ${CONFIG}/mosquitto/config:/mosquitto/config
      - ${CONFIG}/mosquitto/data:/mosquitto/data
      - ${CONFIG}/mosquitto/log:/mosquitto/log
      # - ${CONFIG}/mosquitto:/config
    ports:
      - 1883:1883
    # labels:
    #   - "com.centurylinklabs.watchtower.monitor-only=true"
