services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - 5678:5678
    env_file:
      - ../../.env
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - n8n_net

volumes:
  n8n_data:

networks:
  n8n_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24 