---
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG}/watchtower/config.json:/config.json
    environment:
      - WATCHTOWER_SCHEDULE=0 0 4 * * 0
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:${PUSHOVER_WATCHTOWER}@${PUSHOVER_USER}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      # - WATCHTOWER_LABEL_ENABLE=1          # Only include containers with enable label
    ports:
      - 8190:80
    restart: on-failure

# to force update run the following
# docker run -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once