---

services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - ${CONFIG}/speedtest:/config
    environment:
      - TZ=$TZ
      - PGID=$PGID
      - PUID=$PUID
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
          max-file: "10"
          max-size: "200k"
    restart: unless-stopped
