---

# config
# https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/

services:
  sonarr: #TV show search agent
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${TV}:/media
      - ${TMPMEDIA}/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    # labels:
    #   - "com.centurylinklabs.watchtower.monitor-only=true"
